apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: queue
  namespace: {{ .Values.kafka.namespace }}
  labels:
    strimzi.io/cluster: {{ .Values.kafka.cluster }}
spec:
  partitions: 1
  replicas: 1